### PR TITLE
improve assembly guide

### PR DESCRIPTION
**Pull request by rcooke-warwick**
Change-type: patch
Signed-off-by: Ryan Cooke <ryan@balena.io>

### CODE REVIEW

**Comment by rcooke-warwick** [comment]
@balena-ci rebase

**Comment by rcooke-warwick** [comment]
@balena-ci rebase

**Comment by phckopper** [comment]
We could look into breaking the long steps into smaller subsections in the future.
Otherwise, LGTM for unblocking production.

**Review by phckopper — APPROVED** [review]

**Comment by rcooke-warwick** [comment]
@balena-ci I self-certify!

**Pull request merged**
